spring.datasource.url=jdbc:postgresql://localhost:5433/cadastro_clientes
spring.datasource.username=postgres
spring.datasource.password=12182830

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false